import json
import os
import subprocess
from datetime import datetime
from typing import List, Dict, Optional
from pathlib import Path

class SceneVideoGenerator:
    """
    Vollständiger Video-Generator für Szenen aus JSON-Dateien
    Verarbeitet Keywords, Plant-Parts und erstellt Videos
    """
    
    def __init__(self, config_path: str = "config.json"):
        """Initialisiert den Generator mit Konfiguration"""
        self.config = self.load_config(config_path)
        self.setup_directories()
        
    def load_config(self, config_path: str) -> Dict:
        """Lädt die Konfigurationsdatei"""
        if not os.path.exists(config_path):
            # Fallback-Konfiguration
            return {
                "input_json": "scenes.json",
                "output_dir": "generated_videos",
                "temp_dir": "temp",
                "video_width": 1920,
                "video_height": 1080,
                "fps": 30,
                "audio_enabled": True,
                "watermark_text": "Generated by SceneVideoGenerator"
            }
        
        with open(config_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def setup_directories(self):
        """Erstellt alle benötigten Verzeichnisse"""
        directories = [
            self.config["output_dir"],
            self.config["temp_dir"],
            os.path.join(self.config["temp_dir"], "frames"),
            os.path.join(self.config["temp_dir"], "audio")
        ]
        
        for directory in directories:
            Path(directory).mkdir(parents=True, exist_ok=True)
    
    def load_scenes(self) -> List[Dict]:
        """Lädt Szenen aus der JSON-Datei"""
        json_path = self.config["input_json"]
        
        try:
            with open(json_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            scenes = data.get('scenes', [])
            
            # Validiere jede Szene
            validated_scenes = []
            for i, scene in enumerate(scenes):
                validated = self.validate_scene(scene, i)
                if validated:
                    validated_scenes.append(validated)
            
            print(f"✅ {len(validated_scenes)} von {len(scenes)} Szenen erfolgreich geladen")
            return validated_scenes
            
        except FileNotFoundError:
            print(f"❌ JSON-Datei nicht gefunden: {json_path}")
            return []
        except json.JSONDecodeError as e:
            print(f"❌ Fehler beim Parsen der JSON-Datei: {e}")
            return []
    
    def validate_scene(self, scene: Dict, index: int) -> Optional[Dict]:
        """Validiert eine einzelne Szene"""
        required_fields = ['scene_id', 'keywords', 'plant_part', 'duration']
        
        # Prüfe Pflichtfelder
        for field in required_fields:
            if field not in scene:
                print(f"⚠️  Szene {index}: Fehlendes Feld '{field}' - wird übersprungen")
                return None
        
        # Setze Standardwerte für optionale Felder
        scene.setdefault('background_color', '#000000')
        scene.setdefault('text_color', '#FFFFFF')
        scene.setdefault('font_size', 48)
        scene.setdefault('transition', 'fade')
        scene.setdefault('audio_file', None)
        
        # Validiere Datentypen
        try:
            scene['duration'] = float(scene['duration'])
            if scene['duration'] <= 0:
                print(f"⚠️  Szene {index}: Ungültige Dauer - wird auf 5s gesetzt")
                scene['duration'] = 5.0
        except (ValueError, TypeError):
            scene['duration'] = 5.0
        
        return scene
    
    def generate_scene_video(self, scene: Dict, scene_index: int) -> Optional[str]:
        """Generiert ein Video für eine einzelne Szene"""
        try:
            # Extrahiere Szeneninformationen
            scene_id = scene['scene_id']
            keywords = scene['keywords']
            plant_part = scene['plant_part']
            duration = scene['duration']
            bg_color = scene['background_color']
            text_color = scene['text_color']
            
            # Erstelle Text-Inhalt
            text_content = f"Keywords: {', '.join(keywords)}\nPlant Part: {plant_part}"
            
            # Erstelle temporäre Dateinamen
            temp_video = os.path.join(
                self.config["temp_dir"], 
                f"scene_{scene_index:03d}.mp4"
            )
            
            final_video = os.path.join(
                self.config["output_dir"],
                f"scene_{scene_index:03d}_{plant_part.lower().replace(' ', '_')}.mp4"
            )
            
            # FFmpeg-Befehl zum Erstellen des Videos
            ffmpeg_cmd = [
                'ffmpeg',
                '-f', 'lavfi',
                '-i', f'color=c={bg_color[1:] if bg_color.startswith("#") else bg_color}:'
                      f's={self.config["video_width"]}x{self.config["video_height"]}:'
                      f'd={duration}:r={self.config["fps"]}',
                '-vf', (
                    f"drawtext=text='{text_content}':"
                    f"fontcolor={text_color}:"
                    f"fontsize={scene['font_size']}:"
                    f"x=(w-text_w)/2:y=(h-text_h)/2:"
                    f"fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
                ),
                '-c:v', 'libx264',
                '-preset', 'medium',
                '-crf', '23',
                '-pix_fmt', 'yuv420p',
                '-y',  # Überschreiben ohne Nachfrage
                temp_video
            ]
            
            # Audio hinzufügen falls vorhanden
            if self.config.get('audio_enabled', False) and scene.get('audio_file'):
                if os.path.exists(scene['audio_file']):
                    ffmpeg_cmd = self._add_audio_to_command(ffmpeg_cmd, scene['audio_file'], duration)
            
            # Führe FFmpeg aus
            print(f"🎬 Generiere Szene {scene_index + 1}: {plant_part} ({duration}s)")
            subprocess.run(ffmpeg_cmd, check=True, capture_output=True, text=True)
            
            # Füge Wasserzeichen hinzu falls konfiguriert
            if self.config.get('watermark_text'):
                self._add_watermark(temp_video, final_video)
            else:
                os.rename(temp_video, final_video)
            
            print(f"✅ Szene {scene_index + 1} gespeichert als: {final_video}")
            return final_video
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Fehler bei Szene {scene_index + 1}: {e.stderr}")
            return None
        except Exception as e:
            print(f"❌ Unerwarteter Fehler bei Szene {scene_index + 1}: {e}")
            return None
    
    def _add_audio_to_command(self, base_cmd: List[str], audio_file: str, duration: float) -> List[str]:
        """Erweitert FFmpeg-Befehl um Audio"""
        # Komplexer Befehl für Audio+Video
        return [
            'ffmpeg',
            '-f', 'lavfi',
            '-i', f'color=c=black:s=1920x1080:d={duration}:r=30',
            '-i', audio_file,
            '-filter_complex', (
                f"[0:v]drawtext=text='Video':fontsize=72:x=(w-text_w)/2:y=(h-text_h)/2[v];"
                f"[1:a]atrim=0:{duration},adelay=0|0[a]"
            ),
            '-map', '[v]',
            '-map', '[a]',
            '-c:v', 'libx264',
            '-c:a', 'aac',
            '-shortest',
            '-y',
            base_cmd[-1]  # Output file
        ]
    
    def _add_watermark(self, input_video: str, output_video: str):
        """Fügt Wasserzeichen zum Video hinzu"""
        watermark = self.config.get('watermark_text', '')
        
        watermark_cmd = [
            'ffmpeg',
            '-i', input_video,
            '-vf', f"drawtext=text='{watermark}':fontsize=24:"
                   f"x=10:y=h-text_h-10:fontcolor=white@0.5",
            '-c:a', 'copy',
            '-y',
            output_video
        ]
        
        subprocess.run(watermark_cmd, check=True, capture_output=True)
        os.remove(input_video)  # Lösche temporäre Datei
    
    def generate_final_montage(self, scene_videos: List[str]):
        """Erstellt eine finale Montage aller Szenen"""
        if not scene_videos:
            print("❌ Keine Videos für Montage verfügbar")
            return
        
        # Erstelle Textdatei mit Video-Liste für FFmpeg Concat
        list_file = os.path.join(self.config["temp_dir"], "video_list.txt")
        
        with open(list_file, 'w', encoding='utf-8') as f:
            for video in scene_videos:
                if os.path.exists(video):
                    f.write(f"file '{os.path.abspath(video)}'\n")
        
        # Finales Video
        final_output = os.path.join(
            self.config["output_dir"],
            f"final_montage_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mp4"
        )
        
        # FFmpeg concat Befehl
        concat_cmd = [
            'ffmpeg',
            '-f', 'concat',
            '-safe', '0',
            '-i', list_file,
            '-c', 'copy',
            '-y',
            final_output
        ]
        
        try:
            print("🎞️  Erstelle finale Montage...")
            subprocess.run(concat_cmd, check=True, capture_output=True)
            print(f"✅ Finale Montage gespeichert als: {final_output}")
            
            # Berechne Gesamtdauer
            total_duration = sum(
                float(json.loads(
                    subprocess.run(
                        ['ffprobe', '-v', 'quiet', '-show_entries', 'format=duration',
                         '-of', 'json', video],
                        capture_output=True
                    ).stdout
                )['format']['duration'])
                for video in scene_videos if os.path.exists(video)
            )
            
            print(f"📊 Gesamtdauer: {total_duration:.2f} Sekunden")
            print(f"📊 Anzahl Szenen: {len(scene_videos)}")
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Fehler bei Montage: {e.stderr}")
    
    def generate_all(self):
        """Hauptfunktion: Generiert alle Videos"""
        print("🚀 Starte Video-Generierung...")
        print("=" * 50)
        
        # Lade Szenen
        scenes = self.load_scenes()
        if not scenes:
            print("❌ Keine Szenen zum Verarbeiten gefunden")
            return
        
        # Generiere Videos für jede Szene
        generated_videos = []
        for i, scene in enumerate(scenes):
            video_path = self.generate_scene_video(scene, i)
            if video_path:
                generated_videos.append(video_path)
        
        # Erstelle finale Montage
        if generated_videos and len(generated_videos) > 1:
            self.generate_final_montage(generated_videos)
        
        print("=" * 50)
        print(f"✅ Fertig! {len(generated_videos)} Videos generiert")
        
        # Zusammenfassung
        self.generate_summary_report(scenes, generated_videos)
    
    def generate_summary_report(self, scenes: List[Dict], videos: List[str]):
        """Erstellt eine Zusammenfassung der Generierung"""
        report_path = os.path.join(self.config["output_dir"], "generation_report.txt")
        
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write("Video Generation Report\n")
            f.write("=" * 50 + "\n")
            f.write(f"Generiert am: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Anzahl Szenen: {len(scenes)}\n")
            f.write(f"Erfolgreich generiert: {len(videos)}\n\n")
            
            f.write("Details der Szenen:\n")
            f.write("-" * 50 + "\n")
            
            for i, (scene, video) in enumerate(zip(scenes, videos)):
                f.write(f"\nSzene {i + 1}:\n")
                f.write(f"  ID: {scene.get('scene_id', 'N/A')}\n")
                f.write(f"  Plant Part: {scene.get('plant_part', 'N/A')}\n")
                f.write(f"  Keywords: {', '.join(scene.get('keywords', []))}\n")
                f.write(f"  Dauer: {scene.get('duration', 0)}s\n")
                f.write(f"  Video: {os.path.basename(video) if i < len(videos) else 'FEHLER'}\n")
        
        print(f"📋 Report gespeichert als: {report_path}")


# Beispiel JSON-Datei (scenes.json)
SAMPLE_JSON = {
    "scenes": [
        {
            "scene_id": 1,
            "keywords": ["growth", "photosynthesis", "sunlight"],
            "plant_part": "Leaves",
            "duration": 5,
            "background_color": "#2E8B57",
            "text_color": "#FFFFFF",
            "font_size": 42,
            "transition": "fade",
            "audio_file": "audio/leaves.mp3"
        },
        {
            "scene_id": 2,
            "keywords": ["water", "absorption", "nutrients"],
            "plant_part": "Roots",
            "duration": 7,
            "background_color": "#8B4513",
            "text_color": "#FFFFFF",
            "font_size": 42,
            "transition": "slide"
        },
        {
            "scene_id": 3,
            "keywords": ["reproduction", "pollen", "seeds"],
            "plant_part": "Flowers",
            "duration": 6,
            "background_color": "#FF69B4",
            "text_color": "#000000",
            "font_size": 48
        }
    ]
}


def create_sample_files():
    """Erstellt Beispiel-Dateien für die Demo"""
    # Erstelle Beispiel-JSON
    with open("scenes.json", 'w', encoding='utf-8') as f:
        json.dump(SAMPLE_JSON, f, indent=2, ensure_ascii=False)
    
    # Erstelle Beispiel-Konfiguration
    sample_config = {
        "input_json": "scenes.json",
        "output_dir": "generated_videos",
        "temp_dir": "temp_files",
        "video_width": 1280,
        "video_height": 720,
        "fps": 30,
        "audio_enabled": True,
        "watermark_text": "Botanical Video Generator v1.0"
    }
    
    with open("config.json", 'w', encoding='utf-8') as f:
        json.dump(sample_config, f, indent=2)
    
    print("📁 Beispiel-Dateien erstellt:")
    print("  - scenes.json")
    print("  - config.json")


if __name__ == "__main__":
    print("🌿 Plant Video Generator")
    print("=" * 50)
    
    # Erstelle Beispiel-Dateien falls nicht vorhanden
    if not os.path.exists("scenes.json"):
        create_sample_files()
    
    # Starte die Generierung
    generator = SceneVideoGenerator("config.json")
    generator.generate_all()